# Generated by Django 4.2.4 on 2023-08-27 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='player',
            name='defensiveFouls',
        ),
        migrations.RemoveField(
            model_name='player',
            name='defensiveRebounds',
        ),
        migrations.RemoveField(
            model_name='player',
            name='freeThrowsAttempted',
        ),
        migrations.RemoveField(
            model_name='player',
            name='freeThrowsMade',
        ),
        migrations.RemoveField(
            model_name='player',
            name='isStarter',
        ),
        migrations.RemoveField(
            model_name='player',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='offensiveFouls',
        ),
        migrations.RemoveField(
            model_name='player',
            name='offensiveRebounds',
        ),
        migrations.RemoveField(
            model_name='player',
            name='points',
        ),
        migrations.RemoveField(
            model_name='player',
            name='steals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='threePointersAttempted',
        ),
        migrations.RemoveField(
            model_name='player',
            name='threePointersMade',
        ),
        migrations.RemoveField(
            model_name='player',
            name='turnovers',
        ),
        migrations.RemoveField(
            model_name='player',
            name='twoPointersAttempted',
        ),
        migrations.RemoveField(
            model_name='player',
            name='twoPointersMade',
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starter', models.BooleanField()),
                ('minutes', models.IntegerField()),
                ('points', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('offensiveRebounds', models.IntegerField()),
                ('defensiveRebounds', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('defensiveFouls', models.IntegerField()),
                ('offensiveFouls', models.IntegerField()),
                ('freeThrowsMade', models.IntegerField()),
                ('freeThrowsAttempted', models.IntegerField()),
                ('twoPointersMade', models.IntegerField()),
                ('twoPointersAttempted', models.IntegerField()),
                ('threePointersMade', models.IntegerField()),
                ('threePointersAttempted', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='app.Stats', to='app.player'),
        ),
    ]
