# Generated by Django 4.2.4 on 2023-08-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_player_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shot',
            old_name='is_make',
            new_name='isMake',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='is_starter',
            new_name='isStarter',
        ),
    ]
